apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperledger-peer3
  labels:
    app: hyperledger
    role: peer3
spec:
  replicas: 1
  template:
    metadata:
      name: hyperledger-peer-container
      labels:
        role: peer3
    spec:
      restartPolicy: Always
      containers:
        - name: peer-container3
          imagePullPolicy: Never
          image: hyperledger/fabric-peer:latest
          env:
            - name: CORE_PEER_ID
              value: vp3
            - name: CORE_PEER_DISCOVERY_ROOTNODE
              value: "vp0:7051"
            - name: CORE_SECURITY_ENROLLID
              value: "test_vp2"
            - name: CORE_SECURITY_ENROLLSECRET
              value: "9LKqKH5peurL"
            - name: CORE_PEER_PKI_ECA_PADDR
              value: "member-service:7054"
            - name: CORE_PEER_PKI_TCA_PADDR
              value: "member-service:7054"
            - name: CORE_PEER_PKI_TLSCA_PADDR
              value: "member-service:7054"
          args:
            - sh
            - -c
            - "sleep 10; peer node start"
            # - peer
            # - node
            # - start
